### ISSUE TITLE
Issue while Verifying in Arduino IDE

### ISSUE THREAD

**Issue by GRBlake488** [edgar-bonet/tiny-morse-decoder#1]
Greetings. I am new at this so bare with me. When I run VERIFY in Arduino IDE I get this message:

![image](https://user-images.githubusercontent.com/74614713/99418746-f0941300-28c0-11eb-8135-56d8bb615c86.png)

```text
Arduino: 1.8.13 (Windows 10), Board: "ATtiny25/45/85, ATtiny25, Internal 1 MHz"

sketch_nov15a:189:8: error: 'edge_t' does not name a type; did you mean 'ldiv_t'?
 static edge_t get_edge(void)
        ^~~~~~
        ldiv_t
sketch_nov15a:233:8: error: 'symbol_t' does not name a type
 static symbol_t tokenize(edge_t edge)
        ^~~~~~~~
sketch_nov15a:338:20: error: 'symbol_t' was not declared in this scope
 static char decode(symbol_t symbol)
                    ^~~~~~~~
sketch_nov15a:141:8: error: '__flash' does not name a type; did you mean 'fflush'?
 static __flash const uint16_t dot_times[] = {
        ^~~~~~~
        fflush
C:\Users\georg\Downloads\AT Tiny 85\sketch_nov15a\sketch_nov15a.ino: In function 'void set_delays()':
sketch_nov15a:160:16: error: 'dot_times' was not declared in this scope
     delay_1u = dot_times[speed];
                ^~~~~~~~~
C:\Users\georg\Downloads\AT Tiny 85\sketch_nov15a\sketch_nov15a.ino:160:16: note: suggested alternative: 'init_timer'
     delay_1u = dot_times[speed];
                ^~~~~~~~~
                init_timer
C:\Users\georg\Downloads\AT Tiny 85\sketch_nov15a\sketch_nov15a.ino: At global scope:
sketch_nov15a:294:8: error: '__flash' does not name a type; did you mean 'fflush'?
 static __flash const uint16_t morse_code[CODE_LENGTH] = {
        ^~~~~~~
        fflush
C:\Users\georg\Downloads\AT Tiny 85\sketch_nov15a\sketch_nov15a.ino: In function 'char code_to_char(uint16_t)':
sketch_nov15a:314:13: error: 'morse_code' was not declared in this scope
         if (morse_code[i] == code)
             ^~~~~~~~~~
C:\Users\georg\Downloads\AT Tiny 85\sketch_nov15a\sketch_nov15a.ino:314:13: note: suggested alternative: 'decode'
         if (morse_code[i] == code)
             ^~~~~~~~~~
             decode
C:\Users\georg\Downloads\AT Tiny 85\sketch_nov15a\sketch_nov15a.ino: In function 'char decode(symbol_t)':
sketch_nov15a:338:35: error: 'char decode(symbol_t)' redeclared as different kind of symbol
 static char decode(symbol_t symbol)
                                   ^
C:\Users\georg\Downloads\AT Tiny 85\sketch_nov15a\sketch_nov15a.ino:338:13: note: previous declaration 'char decode'
 static char decode(symbol_t symbol)
             ^~~~~~
C:\Users\georg\Downloads\AT Tiny 85\sketch_nov15a\sketch_nov15a.ino: In function 'int main()':
sketch_nov15a:465:28: error: 'decode' cannot be used as a function
         char c = decode(sym);
                            ^
exit status 1

'edge_t' does not name a type; did you mean 'ldiv_t'?

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by edgar-bonet** [comment]
Hi! Thanks for reporting the issue!

It looks like you copied the program and pasted it straight into the Arduino IDE. This cannot work: the Arduino IDE expects you to type an Arduino sketch, whereas this program is provided as a plain C file. It is not intended to be compiled with the Arduino IDE, but rather with GNU make. See the instructions on [Compiling and uploading][build].

However, we can try to make it compatible with the Arduino IDE. It looks like an empty file with the extension .ino living in the same directory can be enough to convince the IDE to compile the C program as C.

I just pushed a branch for testing this trick. Would you mind giving it a try and reporting back here? It's here: [arduino-compat][].

Regards.

[build]: ..#compiling-and-uploading
[arduino-compat]: ../tree/arduino-compat

**Comment by GRBlake488** [comment]
Well, I don't know what I am doing but it seems to have compiled without errors. I have attached a PDF of the SKETCH.

Since I have never done this before, I may have questions if that is OK?

What about the Library files that are called out? Do I need to also add those separately or will the IDE automatically pull them in?

I am using the AVR USB Mini Programmer from Sparkfun for the AT Tiny 85. Anything I need to change in the Code? What is the specific name of the Programmer i should look for?

https://www.sparkfun.com/products/11801 

[tiny-morse-decoder sketch.pdf](https://github.com/edgar-bonet/tiny-morse-decoder/files/5557865/tiny-morse-decoder.sketch.pdf)

Thanks.

George Blake

**Comment by GRBlake488** [comment]
There is also this document from the Sparkfun web site about the AT Tiny 85. I am sure you know these already but i thought I should include it for reference just in case there is something you don't know.
[Tiny_QuickRef_v2_2.pdf](https://github.com/edgar-bonet/tiny-morse-decoder/files/5557914/Tiny_QuickRef_v2_2.pdf)

**Comment by edgar-bonet** [comment]
> it seems to have compiled without errors.

So you downloaded the arduino-compat branch and it compiled fine? Great!

> I have attached a PDF of the SKETCH.

I don't understand. Why are you attaching this? Do you think I don't have this code? Did you have to make some modifications in order for it to compile and you want to show me the changes you made? I gave it a quick glance, and it looks that you mostly (only maybe?) changed the formatting. Did you change anything else?

Note that a PDF of a source code is pretty useless. I cannot compile it. I cannot run [`git diff`][diff] on it to see exactly what modifications you did. I don't know what I am supposed to do with it.

> What about the Library files that are called out?

This program uses no libraries other than the [avr-libc][]. It doesn't even use the Arduino core library.

> Do I need to also add those separately or will the IDE automatically pull them in?

Unless told to do otherwise, the AVR C compiler links every program it compiles with the avr-libc. The IDE doesn't even have to ask.

> Anything I need to change in the Code?

To change for what purpose? Anything you _want_ to change?

> What is the specific name of the Programmer i should look for?

According the [the documentation of your programmer][usbtiny], if you are using the Arduino IDE, you should select in the Tools / Programmer menu the entry named “USBtinyISP”.

If you want to instead use the provided Makefile, you should change [the definition of `PROGRAMMER`][PROGRAMMER] to this:

```make
PROGRAMMER = -c usbtiny
```

> There is also this document from the Sparkfun web site about the ATtiny85.

That document is not about the ATtiny85: it is about the version of the Arduino core that targets that microcontroller. This program does not use the Arduino core at all.

[diff]: https://git-scm.com/docs/git-diff
[avr-libc]: https://www.nongnu.org/avr-libc/
[usbtiny]: http://highlowtech.org/?p=1801
[PROGRAMMER]: ../blob/bbd587ddbb7b1c960a1c4e8991e7fbb27bdb1006/Makefile#L8

**Comment by GRBlake488** [comment]
Edgar, I have attached the Sketch files with the INO file for you to review. I should have hardware soon to test. If you have a way to test it, I would appreciate your comments.

Thanks for the previous info. Your help is appreciated.

George


[sketch_nov17a.zip](https://github.com/edgar-bonet/tiny-morse-decoder/files/5561874/sketch_nov17a.zip)

**Comment by GRBlake488** [comment]
The question about "Is there anything I need to change?" Was related to using the AVR Tiny Programmer. In case there were any changes to the Code to make it work. I saw in your MAKE file you said to change some parameters for the Tiny 85, Baud rates, etc. so I wanted to make sure I got it right.

When I upload the INO to the Tiny 85 I am supposed to change the Clock Rate to 8 MHz, right? At least that's what I am reading on various sites.

**Comment by edgar-bonet** [comment]
> I have attached the Sketch files with the INO file for you to review.

OK, let's take a look.

* **sketch\_nov17a/tiny-morse-decoder.c**: This seems to be a copy of the version from this repository, with only the line endings changed from Unix style (LF) to Windows style (CRLF).

* **sketch\_nov17a/tiny-morse-decoder/tiny-morse-decoder.c**: Why are you sending two copies of the same program? As far as I can tell, here you just changed the formatting of comments and some white space. Why did you go through the trouble of doing that? The compiler does not care. As far as it is concerned, all three copies of the program (the one in this repo and the two you posted) are identical.

* **sketch\_nov17a/tiny-morse-decoder/tiny-morse-decoder.ino**: Here you wrapped the comment into a `setup()` function. You are then creating a empty function that is not used anywhere. Why? You should define `setup()` and `loop()` when writing an Arduino sketch. This program is not an Arduino sketch. It does not make any use of the Arduino core. It does not need `setup()` nor `loop()`.

* **sketch\_nov17a/tiny-morse-decoder/data/Makefile**: If you are trying to compile the program with the Arduino IDE, you have no use of this file. If you are instead using GNU make, as suggested in the documentation, then you were right to change the definition of `MCU`, you forgot to change `PROGRAMMER`, and you should not have changed anything else.

Specifically, this change was not asked for:

```diff
--- Makefile
+++ sketch_nov17a/tiny-morse-decoder/data/Makefile
@@ -15,8 +15,8 @@
 TARGET = tiny-morse-decoder.elf
 
 # Avrdude expects the ATtiny13A to be called "attiny13".
-ifeq "$(MCU)" "attiny13a"
-    AVRDUDE_MCU = attiny13
+ifeq "$(MCU)" "attiny85"
+    AVRDUDE_MCU = attiny85
 else
     AVRDUDE_MCU = $(MCU)
 endif
```

> The question about "Is there anything I need to change?" Was related to using the AVR Tiny Programmer.

I see. No, there is nothing to change. The programmer is only needed for uploading the compiled program into the microcontroller. It has no influence whatsoever on how you write the program or how you compile it.

> I saw in your MAKE file you said to change some parameters for the Tiny 85

The only parameters that need to be changed when using an ATtiny85 and a USBtinyISP programmer are:

```make
PROGRAMMER = -c usbtiny
MCU = attiny85
```

But again, this is only useful if you are using “make”, not if you are using the Arduino IDE. We are (mis)using the IDE as an alternative to make. The main difference is that instead of configuring it with a Makefile, you configure it by clicking through menus.

> When I upload the INO to the Tiny 85 I am supposed to change the Clock Rate to 8 MHz, right?

As long as the ATtiny is configured to use its internal clock, it should not really matter. The program will set itself to 8&nbsp;MHz. This is the very first think done in `main()`.

Note that setting the correct clock frequency is important when writing an Arduino sketch. This is not an Arduino sketch.

**Comment by GRBlake488** [comment]
All i did was ZIP the Folder where the files were located. I could not send the INO file. Github won't let me, so I ZIPPED the whole file.

The files were probably modified when I used Auto-Format. I will go back and re-compile it without modifying the Sketch file or your code.

Do I have to modify YOUR code for Arduino, or does it work as is? Still new at this. I see some people on the Internet
[tiny-morse-decoder.zip](https://github.com/edgar-bonet/tiny-morse-decoder/files/5562729/tiny-morse-decoder.zip)
 saying you have to change MAIN, etc.?

**Comment by edgar-bonet** [comment]
No, no need to change anything. Just try to compile it as is.

**Comment by edgar-bonet** [comment]
@GRBlake488: Any news on compiling this with the Arduino IDE?

**Comment by GRBlake488** [comment]
I think so. I got the USBTiny to install. I verified the program and then programmed to the board. It flashed and then the LED came on solid but dimmer. I guess that means it is OK? I have not finished the Prototype board yet to try it.

I started a Board with the circuit on it as well as others I have found online. I am creating a touch pad Keyer with your interface. it will use a separate Tone circuit as well as output to a Computer via USB. It will also have a driver circuit so you can transmit code via USB to the transmitter.
[USB KEYER INTERFACE.pdf](https://github.com/edgar-bonet/tiny-morse-decoder/files/5592777/USB.KEYER.INTERFACE.pdf)

**Comment by edgar-bonet** [comment]
> It flashed and then the LED came on solid but dimmer.

This is not expected. On startup and reset, the LED is supposed to flash an invitation to transmit (K = -.-) at the currently selected speed, then go to normal operation. In normal operation, it lights up when the key is held down: the output on pin PB3 is a debounced and inverted copy of the input on pin PB4.

The LED is not supposed to be solid on, unless the key is held down (PB4 low).

> I am creating a touch pad Keyer with your interface.

That looks quite interesting! Will you publish the project?

**Comment by GRBlake488** [comment]
Let me clarify: It isn't the Keyer LED, it's an LED on the AVR Tiny programmer. It was flashing while programming and then went on solid dimly. Not the same as the one tied to the Tiny85.

I am attaching a schematic of the board for you to look at.

[USB KEYER INTERFACE.pdf](https://github.com/edgar-bonet/tiny-morse-decoder/files/5599289/USB.KEYER.INTERFACE.pdf)

**Comment by edgar-bonet** [comment]
Oh, I see. I have no experience with this model of programmer, but if I remember correctly, the Arduino IDE verifies that the program is correctly written to the MCU's flash (it reads it back and compares with what it wrote) and would tell you if there is a mismatch.

**Comment by GRBlake488** [comment]
Here is a video of my hack job prototype.

The AT Tiny 85 program seems to pick up on DITS vs. DASHES better. I try to send an O and you have to get the timing just right or you end up with a T, I, E, etc. Letters with Dashes like S, etc. are much easier.

I have it set for the second to lowest WPM speed. I will set it for the highest and try again.


George Blake

[Keyer.zip](https://github.com/edgar-bonet/tiny-morse-decoder/files/5626707/Keyer.zip)

**Comment by edgar-bonet** [comment]
> Here is a video of my hack job prototype.

Oh, great! I see you managed to get the Arduino IDE build the program. So I assume the issue was fixed by the dummy .ino file. I will merge the branch into master and close this issue.

> you have to get the timing just right

It is not very forgiving, indeed. Since a dit is one unit, and a dah is three units, the program assumes that any pulse shorter than two units is a dit, and anything longer is a dah.

Note that the available keying rates are defined [near the beginning of the program][rates], and you can change them to your liking.

A nice extension could be to make the program automatically adapt to your keying rate, but that is probably not going to be easy. My primary goal here was to see how much I could manage to fit into the ATtiny13A. It has only 1&nbsp;K or flash and 64&nbsp;bytes of RAM, and that is what made the challenge interesting. I was not into trying to make the most functional device, although that could be interesting on a bigger chip, like the ATtiny85.

> or you end up with a T, I, E,

Like in a “TIE fighter”? I knew the Empire was hacking us. :grin:

[rates]: ../blob/0651afa92f42cdc0ce63444b50574d9aaa7f5210/tiny-morse-decoder.c#L41-L45

**Comment by edgar-bonet** [comment]
Fixed by bbd587ddbb7b1c960a1c4e8991e7fbb27bdb1006.

**Comment by GRBlake488** [comment]
Edgar,

Maybe you can help me with another project. You seem very knowledgeable.

I want to output received commands from a PC to an Arduino Nano just like you send out the Serial pin on the ATTiny85.

This is a DDR VFO BFO unit for programming a DDR Synthesizer board.

All I want to do is to confirm and display that the Arduino read and sent the commands to the DDR board.

I just need a Serial output via one pin like your ATTiny85.

Thanks.

George Blake

[Universal VFO-BFO Module.pdf](https://github.com/edgar-bonet/tiny-morse-decoder/files/6030679/Universal.VFO-BFO.Module.pdf)
[20vfobfosource.zip](https://github.com/edgar-bonet/tiny-morse-decoder/files/6030680/20vfobfosource.zip)

**Comment by edgar-bonet** [comment]
> All I want to do is to confirm and display that the Arduino read and sent the commands to the DDR board.

```c++
Serial.println("I did read and send the commands to the DDR board.");
```

but please note that this is unrelated to this repository. There are better venues for asking general Arduino questions.
